# Generated by Django 3.2.5 on 2021-07-15 09:54

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210713_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_photo', models.ImageField(blank=True, null=True, upload_to='media/profile/images/')),
                ('is_business', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=250, null=True)),
                ('registration_file', models.FileField(blank=True, null=True, upload_to='media/profile/business-registration/')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('business_street_and_number', models.CharField(blank=True, max_length=250, null=True)),
                ('business_city', models.CharField(blank=True, max_length=250, null=True)),
                ('business_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('business_state', models.CharField(blank=True, max_length=250, null=True)),
                ('business_country', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('ower_dob', models.DateField(blank=True, null=True)),
                ('owner_phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_license', models.FileField(blank=True, null=True, upload_to='media/profile/licenses/')),
                ('personal_first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_dob', models.DateField(blank=True, null=True)),
                ('personal_passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_passport_copy', models.FileField(blank=True, null=True, upload_to='media/profile/passports/')),
                ('personal_passport_expiry', models.DateField(blank=True, null=True)),
                ('personal_street_and_number', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_city', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('personal_state', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_country', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('personal_social', models.CharField(blank=True, max_length=250, null=True)),
                ('supported_payments', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Mastercard'), (2, 'VISA'), (3, 'Bank Transfer'), (4, 'Cash'), (5, 'Paypal'), (6, 'Travelers Checks')], max_length=11, null=True)),
                ('payout_method', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Paypal'), (2, 'Wise')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.CharField(blank=True, max_length=250, null=True)),
                ('number', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/profile/certificates/')),
                ('expiry', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
