# Generated by Django 3.2.5 on 2021-07-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='listing',
        ),
    ]
