# Generated by Django 3.2.5 on 2021-07-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0045_auto_20210725_0538'),
        ('users', '0011_videos_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
