# Generated by Django 3.2.5 on 2021-07-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
