# Generated by Django 3.2.5 on 2021-07-25 12:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_registered_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='personal_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
