# Generated by Django 3.2.5 on 2021-07-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210725_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ower_dob',
            new_name='owner_dob',
        ),
    ]
