# Generated by Django 3.2.5 on 2021-07-26 10:42

from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_ower_dob_userprofile_owner_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_currency',
            field=models.IntegerField(blank=True, choices=[(1, 'USD'), (2, 'CAD'), (3, 'EUR'), (4, 'JPY'), (5, 'GBP'), (6, 'AUD')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_routing_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wise_account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payout_method',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Wise'), (2, 'Bank Transfer')], max_length=3, null=True),
        ),
    ]
