# Generated by Django 3.2.5 on 2021-07-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_userprofile_payout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
