# Generated by Django 3.2.5 on 2021-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210726_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_routing_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_branch_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
