# Generated by Django 3.2.5 on 2021-07-26 12:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210726_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='supported_payments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Mastercard'), (2, 'VISA'), (3, 'AMEX'), (3, 'Bank Transfer'), (4, 'Cash'), (5, 'Paypal'), (6, 'Wise'), (6, 'Travelers Checks')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='BusinessContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('skype', models.CharField(blank=True, max_length=250, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
