# Generated by Django 3.2.5 on 2021-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210726_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontacts',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
