# Generated by Django 3.2.5 on 2021-07-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_businesscontacts_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontacts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.userprofile'),
        ),
    ]
