# Generated by Django 3.2.5 on 2021-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_businesscontacts_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontacts',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
