# Generated by Django 3.2.5 on 2021-08-01 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_businesscontacts_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('langauge', models.IntegerField(choices=[(1, 'English'), (2, 'German'), (3, 'French'), (4, 'Dutch'), (5, 'Spanish')], default=1)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
