# Generated by Django 3.2.5 on 2021-08-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='langauge',
            new_name='language',
        ),
    ]
