# Generated by Django 3.2.5 on 2021-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210824_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
