# Generated by Django 3.2.5 on 2021-07-15 09:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import listings.models
import multiselectfield.db.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(1, 'Guests travelling together will have the entire unit for themselves'), (2, 'It has multiple rooms, can accomodate many groups of guests')], max_length=250, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('facilities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Air-conditioned public areas'), (2, 'Air-conditioned rooms'), (3, 'Environmentally friendly'), (4, 'Free bicycle'), (5, 'Free parking'), (6, 'Free Wi-Fi'), (7, 'Internet access'), (8, 'Multilingual staff'), (9, 'Parking lot'), (10, 'Smoke-free property'), (11, 'Wireless internet'), (12, 'Baby sitting'), (13, 'Child care'), (14, 'Concierge desk'), (15, 'Dry cleaning'), (16, 'Ironing / Iron board'), (17, 'Laundry'), (18, 'Luggage Room / Storage'), (19, 'Medical assistance'), (20, 'Newspaper'), (21, 'Pet care / Grooming'), (22, 'Valet'), (23, 'Wedding'), (24, 'Conference Room'), (25, 'Dining Area'), (26, 'Fireplace'), (27, 'Kitchen'), (28, 'Library'), (29, 'Lobby'), (30, 'Lounge'), (31, 'Meeting Room'), (32, 'Garden'), (33, 'Hot Spring'), (34, 'Ironing / Ironing Board'), (35, 'Labyrinth'), (36, 'Meditation Garden'), (37, 'Outdoor Shower'), (38, 'Picnic Area'), (39, 'Terrace'), (40, 'ATM / Banking'), (41, 'Bar'), (42, 'Barbeque Facilities'), (43, 'Cafe'), (44, 'Convenience / Grocery Store'), (45, 'Currency Exchange'), (46, 'Honesty Bar'), (47, 'Poolside Bar'), (48, 'Restaurant'), (49, 'Shopping'), (50, 'Special Menu Request'), (51, 'Tour Assistance'), (52, 'Golf Course'), (53, 'Gym'), (54, 'Health Club'), (55, 'Swimming Pool (indoor)'), (56, 'Swimming Pool (outdoor)'), (57, 'Table Tennis'), (58, 'Tennis Court'), (59, 'Volleyball Court'), (60, 'Yoga Deck'), (61, 'Yoga Shala'), (62, 'Yoga Studio'), (63, 'Beauty Salon'), (64, 'Hair Salon'), (65, 'Hot Tub / Jacuzzi'), (66, 'Sauna'), (67, 'Spa'), (68, 'Steam Room'), (69, 'Temazcal'), (70, 'Bicycle Rental'), (71, 'Board Rental'), (72, 'Car Rental'), (73, 'Cell Phone Rental'), (74, 'Laptop Rental')], max_length=212, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(1, 'Single Room'), (2, 'Double Room'), (3, 'Twin Room'), (4, 'Triple Room'), (5, 'Quadruple Room'), (6, 'Dorm')], max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('shared', models.CharField(choices=[(1, 'Private Room'), (2, 'Shared Room')], default=1, max_length=250)),
                ('max_occupancy', models.PositiveIntegerField(default=0)),
                ('facilities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Bunk beds'), (2, 'Double bed'), (3, 'King bed'), (4, 'Queen bed'), (5, 'Single bed'), (6, 'Twin beds'), (7, 'Bathrobe'), (8, 'Bathtub'), (9, 'Hair Dryer'), (10, 'Outdoor Shower'), (11, 'Private Bathroom'), (12, 'Shared Bathroom'), (13, 'Shower'), (14, 'Toiletries'), (15, 'Towels'), (16, 'Air-conditioned Rooms'), (17, 'Coffee / Tea'), (18, 'Desk'), (19, 'Free bottled water'), (20, 'Free Wi-Fi / Computer'), (21, 'In-room Safe'), (22, 'Internet Access'), (23, 'Ironing / Ironing Board'), (24, 'Kitchen'), (25, 'Mini bar'), (26, 'Mosquito Net'), (27, 'Refrigerator'), (28, 'Room Cleaning'), (29, 'Standing / Ceiling Fan'), (30, 'TV'), (31, 'Wardrobe / Closet'), (32, 'Balcony'), (33, 'Fireplace'), (34, 'Hammock'), (35, 'Hot Tub / Jacuzzi'), (36, 'In-Room Dining'), (37, 'Patio'), (38, 'Sauna'), (39, 'Steam Room'), (40, 'Terrace')], max_length=110, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.accommodation')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='accomodation_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='airport_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='airport_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='airport_shuttle',
            field=models.CharField(choices=[(1, 'Included in the price / Free of Charge'), (2, 'Available for additional cost'), (3, 'Not provided')], default=1, max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='airport_shuttle_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='availability_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='child_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='clean_and_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='deposit_policy',
            field=models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='display_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='drinks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Alcoholic Beverages'), (2, 'Coffee'), (3, 'Detox Juices'), (4, 'Soda'), (5, 'Tea'), (6, 'Water')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='excursion_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='extra_payment_todo_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='food_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='foods',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Ayurvedic Food'), (2, 'Fruitarian Food'), (3, 'Gluten Free Food'), (4, 'Halal Food'), (5, 'Lacto-Ovo Vegetarian Food'), (6, 'Lactose-Free Food'), (7, 'Naturopathic Diet Food'), (8, 'Organic Food'), (9, 'Other Dietary Requirements'), (10, 'Paleo Diet Food'), (11, 'Pescatarian Food'), (12, 'Raw Food'), (13, 'Regular Food (Meat, Poultry, Fish)'), (14, 'Seafood'), (15, 'Vegan Food'), (16, 'Vegetarian Food'), (17, 'Whole Food'), (18, 'Yogic Diet Food')], max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='health_hygiene',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='highlights',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='included_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='instruction_duration',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='listing',
            name='instruction_language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='itinerary_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='know_before_you_go',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_group_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='meals',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Breakfast'), (2, 'Brunch'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Snacks'), (6, 'Drinks')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_child_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='min_group_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='not_included_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='private_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='program_duration',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='listing',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='remainder_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='remaining_amount',
            field=models.IntegerField(default=86),
        ),
        migrations.AddField(
            model_name='listing',
            name='safety_checklist',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Use of cleaning chemicals that are effective against coronavirus.'), (2, 'Linens, towels and laundry washed in accordance with local authority guidelines.'), (3, 'Guest accommodation is disinfected between stays.'), (4, 'The accommodation partner we work with follows the guidelines of the local authoritie'), (5, 'Equipment for activities is disinfected before and/or after use.'), (6, 'Cashless payment available.'), (7, 'Physical distancing is maintained.'), (8, 'Instructors maintain a distance from the client at all times possible.'), (9, 'Activities take place outside where possible.'), (10, 'Staff follow all safety protocols as directed by the local government.'), (11, 'Hand sanitizer available in guest rooms and key areas.'), (12, 'Process in place to check the health of guests.'), (13, 'First aid kit available.'), (14, 'A room is available to isolate suspected or infected COVID-19 patients.'), (15, 'Protective masks are available for all staff.'), (16, 'Protective masks available for clients.')], max_length=38, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='skill_level',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='spa_treament_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='spoken_languages',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='media/listings/brochures/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tagline',
            field=models.CharField(blank=True, max_length=47, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=9)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('skype', models.CharField(blank=True, max_length=254, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('portrait', models.ImageField(upload_to='media/staff/')),
                ('featured_portrait', models.ImageField(upload_to='media/staff/')),
                ('is_host', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('listings', models.ManyToManyField(blank=True, null=True, to='listings.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('training_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1932), listings.models.max_value_current_year])),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/rooms/images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.room')),
            ],
        ),
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidoe', models.FileField(blank=True, null=True, upload_to='media/listings/videos/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('default_price', models.PositiveIntegerField(blank=True, null=True)),
                ('price_calculation', models.CharField(max_length=250)),
                ('instant_booking', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.room')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/listings/images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='BedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Single Bed (1 people)'), (2, 'Platform Bed (2 people)'), (3, 'Crib (1 people)'), (4, 'Mid sleeper bed (1 people)'), (5, 'Sofa bed (1 people)'), (6, 'Ottoman Bed (1 people)'), (7, 'Double Bed (2 people)'), (8, 'Folding Bed ( people)'), (9, 'Twin Bed (2 people)'), (10, 'Antique Style Bed (2 people)'), (11, 'Water Bed (2 people)'), (12, 'Queen Size Bed (2 people)'), (13, 'Murphy Bed (2 people)'), (14, 'Cot Bed (1 people)'), (15, 'Trundle Bed (2 people)'), (16, 'Hanging Bed (1 people)'), (17, 'King Size Bed (2 people)'), (18, 'Canopy Bed (2 people)'), (19, 'Bunk Bed (2 people)'), (20, 'L-shaped Bunk Bed (3 people)'), (21, 'Hammock (1 people)')], max_length=53, null=True)),
                ('num_beds', models.PositiveIntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.room')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/accommodations/images/')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.accommodation')),
            ],
        ),
    ]
