# Generated by Django 3.2.5 on 2021-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210715_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='listings',
            field=models.ManyToManyField(blank=True, to='listings.Listing'),
        ),
    ]
