# Generated by Django 3.2.5 on 2021-07-15 10:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_staff_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
