# Generated by Django 3.2.5 on 2021-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='instruction_language',
            field=models.CharField(choices=[(1, 'Included in the price / Free of Charge'), (2, 'Available for additional cost'), (3, 'Not provided')], default=11, max_length=250),
        ),
        migrations.AlterField(
            model_name='listing',
            name='spoken_languages',
            field=models.CharField(choices=[(1, 'Included in the price / Free of Charge'), (2, 'Available for additional cost'), (3, 'Not provided')], default=11, max_length=250),
        ),
    ]
