# Generated by Django 3.2.5 on 2021-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_spoken_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='airport_shuttle',
            field=models.CharField(choices=[(1, 'Included in the price / Free of Charge'), (2, 'Available for additional cost'), (3, 'Not provided')], max_length=250),
        ),
    ]
