# Generated by Django 3.2.5 on 2021-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210715_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='category',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='category_multiple_units',
            field=models.IntegerField(blank=True, choices=[(1, 'Hotel'), (2, 'Hostel'), (3, 'House'), (4, 'Apartment'), (5, 'Ashram'), (6, 'Academy'), (7, 'Cabin'), (8, 'Resort'), (9, 'School'), (10, 'Lodge'), (11, 'Tent'), (12, 'Bungalow'), (13, 'Chalet'), (14, 'Villa'), (15, 'Cabin(boat)'), (16, 'Motel'), (17, 'Inn'), (18, 'Studio'), (19, 'Campus'), (20, 'Recreational Vehicle'), (21, 'Yurt'), (22, 'Retreat Center'), (23, 'Temple'), (24, 'Monastery'), (25, 'Cottage'), (26, 'Campsite'), (27, 'Various Accommodations'), (28, 'Castle'), (29, 'Barn'), (30, 'Ranch'), (31, 'Bed and Breakfast'), (32, 'Treehouse'), (33, 'Boat'), (34, 'Farm')], null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='category_private_unit',
            field=models.IntegerField(blank=True, choices=[(1, 'House'), (2, 'Apartment'), (3, 'Cabin'), (4, 'Lodge'), (5, 'Tent'), (6, 'Bungalow'), (7, 'Chalet'), (8, 'Villa'), (9, 'Cabin(boat)'), (10, 'Studio'), (11, 'Recreational Vehicle'), (12, 'Yurt'), (13, 'Cottage'), (14, 'Various Accommodations'), (15, 'Barn'), (16, 'Ranch'), (17, 'Boat')], null=True),
        ),
        migrations.AlterField(
            model_name='bedconfig',
            name='bed_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Single Bed (1 people)'), (2, 'Platform Bed (2 people)'), (3, 'Crib (1 people)'), (4, 'Mid sleeper bed (1 people)'), (5, 'Sofa bed (1 people)'), (6, 'Ottoman Bed (1 people)'), (7, 'Double Bed (2 people)'), (8, 'Folding Bed ( people)'), (9, 'Twin Bed (2 people)'), (10, 'Antique Style Bed (2 people)'), (11, 'Water Bed (2 people)'), (12, 'Queen Size Bed (2 people)'), (13, 'Murphy Bed (2 people)'), (14, 'Cot Bed (1 people)'), (15, 'Trundle Bed (2 people)'), (16, 'Hanging Bed (1 people)'), (17, 'King Size Bed (2 people)'), (18, 'Canopy Bed (2 people)'), (19, 'Bunk Bed (2 people)'), (20, 'L-shaped Bunk Bed (3 people)'), (21, 'Hammock (1 people)')], null=True),
        ),
    ]
