# Generated by Django 3.2.5 on 2021-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20210716_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/images/'),
        ),
    ]
