# Generated by Django 3.2.5 on 2021-07-16 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/listings/images/'),
        ),
        migrations.AlterField(
            model_name='listingpackage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='listings.listing'),
        ),
    ]
