# Generated by Django 3.2.5 on 2021-07-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20210716_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingvideo',
            old_name='vidoe',
            new_name='video',
        ),
    ]
