# Generated by Django 3.2.5 on 2021-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_rename_vidoe_listingvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
