# Generated by Django 3.2.5 on 2021-07-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_listing'),
        ('listings', '0016_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
