# Generated by Django 3.2.5 on 2021-07-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_listing'),
        ('listings', '0017_listing_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='host_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
