# Generated by Django 3.2.5 on 2021-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_staff_host_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='listings',
        ),
        migrations.AddField(
            model_name='listing',
            name='staff',
            field=models.ManyToManyField(blank=True, to='listings.Staff'),
        ),
    ]
