# Generated by Django 3.2.5 on 2021-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20210719_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='airport_shuttle_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
