# Generated by Django 3.2.5 on 2021-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_alter_listing_airport_shuttle_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='staff',
        ),
        migrations.AddField(
            model_name='listing',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='listings.Staff'),
        ),
        migrations.AddField(
            model_name='listing',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='listings.Staff'),
        ),
    ]
