# Generated by Django 3.2.5 on 2021-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_listing_remainder_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='days_to_pay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
