# Generated by Django 3.2.5 on 2021-07-21 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listing_days_to_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='remaining_amount',
        ),
        migrations.AlterField(
            model_name='listing',
            name='days_to_pay',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='deposit_policy',
            field=models.PositiveIntegerField(blank=True, default=14, null=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='remainder_due',
            field=models.IntegerField(blank=True, choices=[(1, 'On Arrival'), (2, 'On Depature'), (3, 'Specified Days Before Arrival')], null=True),
        ),
    ]
