# Generated by Django 3.2.5 on 2021-07-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20210721_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
