# Generated by Django 3.2.5 on 2021-07-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_user'),
        ('listings', '0026_auto_20210721_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
