# Generated by Django 3.2.5 on 2021-07-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_accommodation_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationimages',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.accommodation'),
        ),
    ]
