# Generated by Django 3.2.5 on 2021-07-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_alter_accommodationimages_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
