# Generated by Django 3.2.5 on 2021-07-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedconfig',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='listings.room'),
        ),
    ]
