# Generated by Django 3.2.5 on 2021-07-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_auto_20210722_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedcombo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configcombos', to='listings.room'),
        ),
        migrations.AlterField(
            model_name='bedcombo',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='listings.bedconfig'),
        ),
    ]
