# Generated by Django 3.2.5 on 2021-07-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_auto_20210723_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedconfigbranch',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.room'),
        ),
    ]
