# Generated by Django 3.2.5 on 2021-07-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_alter_bedcombo_bed_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedconfig',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_configs', to='listings.room'),
        ),
    ]
