# Generated by Django 3.2.5 on 2021-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_alter_bedconfig_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='max_occupancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
