# Generated by Django 3.2.5 on 2021-07-24 10:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_accommodation_max_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='yoga_style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Ashtanga Yoga'), (2, 'Vinyasa Yoga'), (3, 'Hatha Yoga'), (4, 'Kundalini Yoga'), (5, 'Yin Yoga'), (6, 'Integral Yoga'), (7, 'Nidra Yoga')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
