# Generated by Django 3.2.5 on 2021-07-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0042_auto_20210724_0621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingVideo',
        ),
    ]
