# Generated by Django 3.2.5 on 2021-07-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_videos_approved'),
        ('listings', '0044_listing_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='videos',
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/listings/videos/')),
                ('approved', models.BooleanField(default=False)),
                ('listings', models.ManyToManyField(blank=True, related_name='videos', to='listings.Listing')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.userprofile')),
            ],
        ),
    ]
