# Generated by Django 3.2.5 on 2021-07-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_businesscontacts_email'),
        ('listings', '0045_auto_20210725_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.userprofile'),
        ),
    ]
