# Generated by Django 3.2.5 on 2021-07-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_alter_staff_host_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='listings.staff'),
        ),
    ]
