# Generated by Django 3.2.5 on 2021-07-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_alter_skill_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
