# Generated by Django 3.2.5 on 2021-07-27 12:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0049_listing_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Included in the price / Free of Charge'), (2, 'Available for additional cost'), (3, 'Not provided')], null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='yoga_style',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Ashtanga Yoga'), (2, 'Vinyasa Yoga'), (3, 'Hatha Yoga'), (4, 'Kundalini Yoga'), (5, 'Yin Yoga'), (6, 'Integral Yoga'), (7, 'Nidra Yoga'), (8, 'Bikram / Hot Yoga'), (9, 'AcroYoga'), (10, 'Baptiste Yoga'), (11, 'Forrest Yoga'), (12, 'Jivamukti Yoga'), (13, 'Power Yoga'), (14, 'Rocket Yoga'), (15, 'Tibetan Yoga'), (16, 'Zen Yoga'), (17, 'Iyengar Yoga'), (18, 'Tantra Yoga'), (19, 'Alignment Yoga'), (20, 'Ananda Yoga'), (21, 'Chair Yoga'), (22, 'Chakra Yoga'), (23, 'Critical Alignment Yoga'), (24, 'Dru Yoga'), (25, 'Ganja Yoga'), (26, 'Japa Yoga'), (27, 'Kashmir Yoga'), (28, 'Kripalu Yoga'), (29, 'Laughter Yoga'), (30, 'Laya Yoga'), (31, 'Nada Yoga'), (32, 'Nidra Yoga'), (33, 'Para Yoga'), (34, 'Partnet Yoga'), (35, 'Restorative Yoga'), (36, 'Satyananda Yoga'), (37, 'Sivananda Yoga'), (38, 'Somatic Yoga'), (39, 'Thai Yoga'), (40, 'Therapeutic Yoga'), (41, 'Tibetan Yoga'), (42, 'Transformational Yoga'), (43, 'Viniyoga'), (44, 'Aerial Yoga'), (45, 'Chakra Yoga'), (46, 'Vipassana Yoga'), (47, 'Anusara Yoga')], max_length=131, null=True),
        ),
    ]
