# Generated by Django 3.2.5 on 2021-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0050_auto_20210727_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpackage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Budget Retreats'), (2, 'Luxury Holidays'), (3, 'All-Inclusive Yoga Retreats'), (4, 'Online Experiences'), (5, 'Travel Experiences')], null=True),
        ),
    ]
