# Generated by Django 3.2.5 on 2021-07-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_auto_20210728_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingpackage',
            name='date',
        ),
    ]
