# Generated by Django 3.2.5 on 2021-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0052_remove_listingpackage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpackage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
