# Generated by Django 3.2.5 on 2021-07-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0054_auto_20210728_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('slots', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='packageprices',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='listings.listingpackage'),
        ),
        migrations.AddField(
            model_name='packageprices',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='listings.custompricerequest'),
        ),
    ]
