# Generated by Django 3.2.5 on 2021-07-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0055_auto_20210728_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageprices',
            name='req',
        ),
        migrations.AddField(
            model_name='custompricerequest',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqs', to='listings.packageprices'),
        ),
    ]
