# Generated by Django 3.2.5 on 2021-07-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0057_auto_20210729_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageprices',
            name='req',
        ),
        migrations.AddField(
            model_name='custompricerequest',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqs', to='listings.listingpackage'),
        ),
    ]
