# Generated by Django 3.2.5 on 2021-07-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0058_auto_20210729_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageprices',
            name='reqs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='listings.custompricerequest'),
        ),
    ]
