# Generated by Django 3.2.5 on 2021-08-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0060_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custompricerequest',
            old_name='slots',
            new_name='max_slots',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='daily_data',
        ),
        migrations.AddField(
            model_name='custompricerequest',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custompricerequest',
            name='used_slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.custompricerequest'),
        ),
        migrations.DeleteModel(
            name='PackagePrices',
        ),
    ]
