# Generated by Django 3.2.5 on 2021-08-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0061_auto_20210805_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='conditional',
            field=models.BooleanField(default=False),
        ),
    ]
