# Generated by Django 3.2.5 on 2021-08-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0062_inquiry_conditional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='conditional',
            new_name='is_conditional',
        ),
    ]
