# Generated by Django 3.2.5 on 2021-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0064_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_unread',
            field=models.BooleanField(default=True),
        ),
    ]
