# Generated by Django 3.2.5 on 2021-08-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210804_0539'),
        ('listings', '0065_messages_is_unread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.AddField(
            model_name='messages',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.customer'),
        ),
        migrations.AddField(
            model_name='messages',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.userprofile'),
        ),
    ]
