# Generated by Django 3.2.5 on 2021-08-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210804_0539'),
        ('listings', '0066_auto_20210806_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.userprofile'),
        ),
    ]
