# Generated by Django 3.2.5 on 2021-08-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210804_0539'),
        ('listings', '0067_auto_20210806_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='msg',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='host',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='inquiry',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.customer')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.conversation'),
            preserve_default=False,
        ),
    ]
