# Generated by Django 3.2.5 on 2021-08-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0068_auto_20210806_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='guest',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='conversation',
            name='inquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.inquiry'),
        ),
    ]
