# Generated by Django 3.2.5 on 2021-08-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0069_auto_20210806_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='inquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='listings.inquiry'),
        ),
    ]
