# Generated by Django 3.2.5 on 2021-08-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0070_alter_conversation_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.conversation'),
        ),
    ]
