# Generated by Django 3.2.5 on 2021-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0071_alter_messages_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='from_host',
            field=models.BooleanField(default=False),
        ),
    ]
