# Generated by Django 3.2.5 on 2021-08-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0072_messages_from_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='shared',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Shared')], default=1),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/messages/attachments/')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='listings.messages')),
            ],
        ),
    ]
