# Generated by Django 3.2.5 on 2021-08-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0073_auto_20210807_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='is_unread',
            new_name='is_unread_customer',
        ),
    ]
