# Generated by Django 3.2.5 on 2021-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0074_rename_is_unread_messages_is_unread_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_unread_host',
            field=models.BooleanField(default=True),
        ),
    ]
