# Generated by Django 3.2.5 on 2021-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0076_inquiry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
