# Generated by Django 3.2.5 on 2021-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0077_inquiry_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
