# Generated by Django 3.2.5 on 2021-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0078_inquiry_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='due_date',
            field=models.IntegerField(choices=[(1, 'On Arrival'), (2, 'On Departure'), (3, 'Before Arrival')], default=1),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='number_of_days_before_arrival',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='required_deposit',
            field=models.IntegerField(default=14),
        ),
    ]
