# Generated by Django 3.2.5 on 2021-08-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0080_rename_due_date_inquiry_to_be_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='remaining_amount',
            field=models.IntegerField(default=86),
        ),
    ]
