# Generated by Django 3.2.5 on 2021-08-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0081_inquiry_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
