# Generated by Django 3.2.5 on 2021-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0082_inquiry_deposit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
