# Generated by Django 3.2.5 on 2021-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0083_inquiry_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='payment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
