# Generated by Django 3.2.5 on 2021-08-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0085_remove_inquiry_payment_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='host_declined',
            field=models.BooleanField(default=False),
        ),
    ]
