# Generated by Django 3.2.5 on 2021-08-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0087_inquiry_deposit_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='commission_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
