# Generated by Django 3.2.5 on 2021-08-10 09:26

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0088_auto_20210810_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='invoice_no',
            field=models.CharField(blank=True, default=listings.models.increment_invoice_number, max_length=500, null=True),
        ),
    ]
