# Generated by Django 3.2.5 on 2021-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0089_alter_inquiry_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deposit_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='remaining_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
