# Generated by Django 3.2.5 on 2021-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0090_auto_20210810_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deposit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
