# Generated by Django 3.2.5 on 2021-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0091_inquiry_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
