# Generated by Django 3.2.5 on 2021-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0093_inquiry_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='deposit_payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
