# Generated by Django 3.2.5 on 2021-08-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0097_alter_inquiry_commission_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ranking',
        ),
        migrations.AddField(
            model_name='listing',
            name='commission',
            field=models.IntegerField(default=14),
        ),
    ]
