# Generated by Django 3.2.5 on 2021-08-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0098_auto_20210810_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='commission',
        ),
        migrations.AddField(
            model_name='listing',
            name='ranking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
