# Generated by Django 3.2.5 on 2021-08-10 12:14

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0099_auto_20210810_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
