# Generated by Django 3.2.5 on 2021-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0100_inquiry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='to_be_paid',
            field=models.IntegerField(blank=True, choices=[(1, 'On Arrival'), (2, 'On Departure'), (3, 'Before Arrival')], default=1, null=True),
        ),
    ]
