# Generated by Django 3.2.5 on 2021-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0101_alter_inquiry_to_be_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deposit_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
