# Generated by Django 3.2.5 on 2021-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0102_inquiry_deposit_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
