# Generated by Django 3.2.5 on 2021-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0103_alter_inquiry_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='commission_percent',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
    ]
