# Generated by Django 3.2.5 on 2021-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0104_listing_commission_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='remaining_payout_amount',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='remaining_payout_date',
        ),
        migrations.AlterField(
            model_name='listing',
            name='remainder_due',
            field=models.IntegerField(blank=True, choices=[(1, 'On Arrival'), (2, 'On Depature'), (3, 'Specified Days Before Arrival')], default=1, null=True),
        ),
    ]
