# Generated by Django 3.2.5 on 2021-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0105_auto_20210811_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
