# Generated by Django 3.2.5 on 2021-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0106_inquiry_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='commission_percent',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
    ]
