# Generated by Django 3.2.5 on 2021-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0107_inquiry_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deposit_payout_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
