# Generated by Django 3.2.5 on 2021-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0108_inquiry_deposit_payout_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deposit_payout_complete',
            field=models.BooleanField(default=False),
        ),
    ]
