# Generated by Django 3.2.5 on 2021-08-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0109_inquiry_deposit_payout_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='depsoit_payout_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
