# Generated by Django 3.2.5 on 2021-08-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0111_inquiry_net_deposit_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='deposit_payout_amount_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
