# Generated by Django 3.2.5 on 2021-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0113_stripeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='deposit_paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
