# Generated by Django 3.2.5 on 2021-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0119_auto_20210815_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
