# Generated by Django 3.2.5 on 2021-08-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0120_alter_review_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='inquiry',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='listings.inquiry'),
            preserve_default=False,
        ),
    ]
