# Generated by Django 3.2.5 on 2021-08-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210804_0539'),
        ('listings', '0122_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to='users.Customer'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
