# Generated by Django 3.2.5 on 2021-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0125_auto_20210817_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='from_owner',
            field=models.BooleanField(default=False),
        ),
    ]
