# Generated by Django 3.2.5 on 2021-08-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0127_listing_viewed_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
