# Generated by Django 3.2.5 on 2021-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0128_pagehits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehits',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
