# Generated by Django 3.2.5 on 2021-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0129_pagehits_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='viewed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videos',
            name='viewed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
