# Generated by Django 3.2.5 on 2021-08-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0130_auto_20210819_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='viewed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
