# Generated by Django 3.2.5 on 2021-08-19 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0132_listing_updated_after_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='progress',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
