# Generated by Django 3.2.5 on 2021-08-19 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0133_listing_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
