# Generated by Django 3.2.5 on 2021-08-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0134_alter_listing_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='progress',
        ),
    ]
