# Generated by Django 3.2.5 on 2021-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0135_remove_listing_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='host_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
