# Generated by Django 3.2.5 on 2021-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0136_inquiry_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='admin_approval_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
