# Generated by Django 3.2.5 on 2021-08-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0138_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lowest_price',
            field=models.IntegerField(default=0),
        ),
    ]
