# Generated by Django 3.2.5 on 2021-08-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0139_listing_lowest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
