# Generated by Django 3.2.5 on 2021-08-23 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0140_listing_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
