# Generated by Django 3.2.5 on 2021-08-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0143_salesgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesgoal',
            old_name='goal',
            new_name='monthly_goal',
        ),
        migrations.AddField(
            model_name='salesgoal',
            name='yearly_goal',
            field=models.IntegerField(default=0),
        ),
    ]
