# Generated by Django 3.2.5 on 2021-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0144_auto_20210823_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
