# Generated by Django 3.2.5 on 2021-08-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0146_videos_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
