# Generated by Django 3.2.5 on 2021-08-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0148_auto_20210824_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpackage',
            name='available_all_year',
            field=models.BooleanField(default=False),
        ),
    ]
