# Generated by Django 3.2.5 on 2021-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0149_listingpackage_available_all_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingpackage',
            name='available_all_year',
        ),
        migrations.AddField(
            model_name='listing',
            name='available_all_year',
            field=models.BooleanField(default=False),
        ),
    ]
