# Generated by Django 3.2.5 on 2021-08-25 10:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0150_auto_20210824_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpackage',
            name='price_calculation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
