# Generated by Django 3.2.5 on 2021-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0151_alter_listingpackage_price_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='instant_booking',
            field=models.BooleanField(default=False),
        ),
    ]
