# Generated by Django 3.2.5 on 2021-08-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0154_auto_20210826_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
