# Generated by Django 3.2.5 on 2021-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0158_auto_20210828_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
