# Generated by Django 3.2.5 on 2021-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0159_alter_listing_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_unread_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_unread_host',
            field=models.BooleanField(default=True),
        ),
    ]
