# Generated by Django 3.2.5 on 2021-08-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0160_auto_20210830_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='original_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
