# Generated by Django 3.2.5 on 2021-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0161_messages_original_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/blog/images/')),
            ],
        ),
    ]
