# Generated by Django 3.2.5 on 2021-08-30 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0162_blogphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogphotos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
