# Generated by Django 3.2.5 on 2021-08-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0163_blogphotos_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogphotos',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='owner_notes',
            new_name='staff_notes',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='owner_notes',
            new_name='staff_notes',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='owner_notes',
            new_name='staff_notes',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='owner_notes',
            new_name='staff_notes',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='owner_notes',
            new_name='staff_notes',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='owner_notes',
            new_name='staff_notes',
        ),
    ]
