# Generated by Django 3.2.5 on 2021-08-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0164_auto_20210830_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
