# Generated by Django 3.2.5 on 2021-09-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0165_listing_updated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='use_place_id',
            field=models.BooleanField(default=False),
        ),
    ]
