# Generated by Django 3.2.5 on 2021-09-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0166_auto_20210902_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='use_place_id',
        ),
    ]
